channels:
  - conda-forge
dependencies:
  - click=7.1
  - django=4.0
  - django-extensions=1!3.1.7
  - dask
  - distributed==2022.5.0
  - foo[subdir=linux-64,version='>=1.0']
  - pytest==6.2.5
  - pip:
      - certificates
      - pytest 
