channels:
  - conda-forge
  - mmeyer
dependencies:
  - click=7.1
  - dask
  - distributed==2022.8.0
  - foo[subdir=linux-64,version='>=1.0']
  - pytest==7.1.2
  - pip:
      - certificates
      - pytest 
