channels:
  - conda-forge
  - mmeyer
dependencies:
  - click=8.1.3
  - dask
  - distributed==2022.5.0
  - foo[subdir=linux-64,version='>=1.0']
  - pytest==7.1.2
  - pip:
      - certificates
      - pytest 
