channels:
  - conda-forge
  - mmeyer
dependencies:
  - click=7.1
  - dask
  - distributed==2022.5.0
  - foo[subdir=linux-64,version='>=1.0']
  - foo==1.0=py27_0
  - conda-forge::foo==2.7.1[build=py2*]
  - conda-forge/testdir::foo==2.7.1[build=py2*]
  - conda-forge::foo==2.7.1
  - pip:
      - certificates
      - pytest 
